[build]
  functions = "functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[functions.app]
  external_node_modules = ["ejs", "express", "cookie-parser", "morgan", "serverless-http"]
