[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200


[[plugins]]
  package = "@netlify/plugin-functions-install-core"